[package]
name = "sweepx-catalog"
version.workspace = true
description = "Built-in cleaner catalog loading and compatibility checks for SweepX"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde_json = { version = "1.0.145", features = ["preserve_order"] }
sha2 = "0.10.9"
sweepx-cleaner-schema = { version = "0.1.0", path = "../sweepx-cleaner-schema" }
thiserror = "2.0.16"

[dev-dependencies]
serde_json = { version = "1.0.145", features = ["preserve_order"] }
