[package]
name = "sweepx-platform-windows"
version.workspace = true
description = "Windows filesystem scanning backend for SweepX"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sweepx-platform = { version = "0.1.0", path = "../sweepx-platform" }
sweepx-model = { version = "0.1.0", path = "../sweepx-model" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
  "Wdk_Foundation",
  "Wdk_Storage_FileSystem",
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_IO",
  "Win32_System_WindowsProgramming",
] }
