[package]
name = "sweepx-platform-linux"
version.workspace = true
description = "Linux filesystem scanning backend for SweepX"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
libc = "0.2.189"
sweepx-model = { version = "0.1.0", path = "../sweepx-model" }
sweepx-platform = { version = "0.1.0", path = "../sweepx-platform" }

[dev-dependencies]
libloading = "0.8.9"
sha2 = "0.10.9"
sweepx-fixtures = { version = "0.1.0", path = "../sweepx-fixtures" }
tempfile = "3.21.0"
