[package]
name = "sweepx-platform-linux"
version.workspace = true
description = "Linux filesystem scanning backend for SweepX"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sweepx-model = { version = "0.1.0", path = "../sweepx-model" }
sweepx-platform = { version = "0.1.0", path = "../sweepx-platform" }

[dev-dependencies]
tempfile = "3.21.0"
