// `fs` and `Path` serve the fixture helper alone, so they follow it behind the same gate.
#[cfg(windows)]
use std::fs;
#[cfg(windows)]
use std::path::Path;

use assert_cmd::Command;
// Only the two `cfg(windows)` relay tests build a fixture; the flag-visibility test below runs
// everywhere and needs neither. Gate the import and the helper the same way the tests are gated,
// or `-D warnings` fails the linux and macOS runners on an unused import and a dead function.
#[cfg(windows)]
use tempfile::TempDir;

fn cli_command() -> Command {
    Command::cargo_bin("sweepx").expect("binary available")
}

#[cfg(windows)]
fn fixture_root(temp: &Path) -> std::path::PathBuf {
    let root = temp.join("scan-root");
    fs::create_dir_all(&root).unwrap();
    fs::write(root.join("sample.txt"), b"sweepx").unwrap();
    root
}

/// Output written while a relay is active must land in the file, not on the console.
///
/// This is the property that makes `--elevate` usable at all. Measured on Windows before the fix:
/// an elevated scan completed with exit code 0 and delivered **zero bytes** to the caller, because
/// `ShellExecuteExW` with `runas` gives the child a new console that closes when it exits. The
/// redirect is exercised here without elevation, so the half that can be tested unprivileged is
/// actually tested rather than left to the one manual run.
#[cfg(windows)]
#[test]
fn a_relayed_run_writes_its_output_to_the_named_file() {
    let temp = TempDir::new().unwrap();
    let root = fixture_root(temp.path());
    let destination = temp.path().join("relayed-stdout");

    let mut cmd = cli_command();
    cmd.arg("--format")
        .arg("json")
        .arg("--relay-stdout-to")
        .arg(&destination)
        .arg("scan")
        .arg(&root);
    let output = cmd.assert().get_output().clone();

    assert!(
        output.stdout.is_empty(),
        "a relayed run must not also write to the console, or the parent would duplicate it"
    );
    let relayed = fs::read(&destination).expect("the relay file must exist");
    let parsed: serde_json::Value =
        serde_json::from_slice(&relayed).expect("the relayed bytes must be the complete document");
    assert_eq!(
        parsed["kind"], "scan.result",
        "the whole result must survive redirection, not a truncated prefix"
    );
}

/// A relay destination that already exists is refused, and the existing file is left alone.
///
/// The destination is normally generated by the parent inside a fresh private directory, so an
/// existing file means something is wrong. Refusing rather than truncating is what keeps an
/// elevated SweepX from being usable as a "write this file as administrator" primitive: the flag is
/// hidden, but hidden is not a security boundary.
#[cfg(windows)]
#[test]
fn a_relay_destination_that_exists_is_never_overwritten() {
    let temp = TempDir::new().unwrap();
    let root = fixture_root(temp.path());
    let victim = temp.path().join("precious.txt");
    fs::write(&victim, b"must survive").unwrap();

    let mut cmd = cli_command();
    cmd.arg("--format")
        .arg("json")
        .arg("--relay-stdout-to")
        .arg(&victim)
        .arg("scan")
        .arg(&root);
    let output = cmd.assert().failure().get_output().clone();

    assert_eq!(
        fs::read(&victim).unwrap(),
        b"must survive",
        "an existing file must be preserved byte-for-byte"
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("could not redirect output"),
        "the refusal must say why; got {stderr}"
    );
}

/// The relay flag stays out of `--help`, because it is a protocol between two SweepX processes.
///
/// Documenting it would invite callers to pass their own destination, which is exactly the usage
/// the parent-generated path exists to prevent.
#[test]
fn the_relay_flag_is_not_advertised_to_users() {
    let mut cmd = cli_command();
    cmd.arg("--help");
    let output = cmd.assert().get_output().stdout.clone();
    let help = String::from_utf8_lossy(&output);

    assert!(
        !help.contains("relay-stdout-to"),
        "an internal flag must not appear in help"
    );
    assert!(
        help.contains("--elevate"),
        "the user-facing elevation flag must still be documented"
    );
}
