[package]
name = "sweepx-platform-macos"
version.workspace = true
description = "macOS filesystem scanning backend for SweepX"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sweepx-platform = { version = "0.1.0", path = "../sweepx-platform" }
sweepx-model = { version = "0.1.0", path = "../sweepx-model" }
