[package]
name = "sweepx-platform"
version.workspace = true
description = "Cross-platform filesystem scanning contracts for SweepX"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
sweepx-model = { version = "0.0.1", path = "../sweepx-model" }
thiserror = "2.0.16"
